### ISSUE TITLE
Getting access to wall.post method

### ISSUE THREAD

**Issue by vkudyushev** [DarkXaHTeP/vk-auth#10]
Thanks for this library!
Can I get access to wall.post (https://vk.com/dev/wall.post) method with this library?

**Comment by DarkXaHTeP** [comment]
Hi @vadimk-design, the library is used for obtaining token with desired permissions ('wall' in your case). Since it performs authentication as mobile/standalone app, you will be able to post to wall. After you have token you can make plain ajax requests to vk api, or use some wrapper library like [this npm package](https://www.npmjs.com/package/vkontakte).

Please let me know if I got you wrong

**Comment by vkudyushev** [comment]
Thanks!!!
